### ISSUE TITLE
Update doc for complexe use case for AtoumAdapter

### ISSUE THREAD

**Issue by tyx** [rezzza/mock-extension#2]

**Comment by extdevelopment** [comment]
Can you help me?
I would like to to redefine method with test return value in my mock service, but this way not successful.
```php
$mock = $this->mocker->mockService(
    'xx.route.service',
    new AtoumAdapter(\Xx\XxBoundle\Service\Route')
);
$mock->getMockController()->getCity = function($zip) {
    return array("name" => "NewCity");
};
```

**Comment by tyx** [comment]
Hi ! It should work !

The result should be an atoum mock. What result do you get ?

**Comment by extdevelopment** [comment]
@tyx Thx for the answer.
You are right, really works.
It was the fault in my return data structure.

**Comment by shouze** [comment]
Ok so @extdevelopment  I close this one ;)

**Comment by extdevelopment** [comment]
@shouze 
@tyx opened this Issue on Aug 12 2014, not me
